# Generated by Django 2.0.7 on 2018-07-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_auto_20180713_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='alunos_fotos'),
        ),
    ]
