# Generated by Django 2.0.7 on 2018-07-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=30)),
                ('subject', models.CharField(choices=[('QUI', 'Química'), ('FIS', 'Física'), ('BIO', 'Biologia'), ('MAT', 'Matemática'), ('POR', 'Português'), ('RED', 'Redação'), ('HIS', 'História'), ('GEO', 'Geografia')], default='QUI', max_length=3)),
            ],
        ),
    ]
