# Generated by Django 2.0.7 on 2018-07-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiais', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materiais/'),
        ),
    ]
